# Generated by Django 2.1.8 on 2019-08-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testapp", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=31, unique=True
            ),
        )
    ]
