# Generated by Django 2.1.8 on 2019-08-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("testapp", "0002_tag_name_unique")]

    operations = [
        migrations.AlterModelOptions(
            name="tag", options={"ordering": ["name"]}
        )
    ]
